# **Bronze Layer**

In [1]:
import pandas as pd

**1) Load the orders_raw dataset and inspect the first few rows to confirm the data structure and contents.**

In [2]:
df_orders = pd.read_excel("supplychain_raw.xlsx", sheet_name="orders_raw")

Displaying head to inspect

In [3]:
df_orders.head()

,order_id_raw,order_dt_raw,cust_region_raw,sku_raw,qty_raw,unit_price_raw,supplier_raw,promise_ship_dt_raw,currency_raw,order_channel_raw,promo_code_raw,customer_id_raw
0,ORD-1000,2026.01.05,SOUTH,SKU-A499,1 pcs,$155.94,SUP10,20260107,usd,Marketplace,NaN,C00583
1,Ord-1001,20-Jan-26,west,a354,01,"93,99",SUP-002,25-01-2026,NaN,NaN,NaN,C00029
2,ORD1002,Jan 16 2026,west,D674,4,139.35$,SUP-007,21-01-2026,$,NaN,FREESHIP,C00288
3,ORD1003,01/20/26,US-West,E846,1 pcs,"243,48",SUP03,NaN,usd,Marketplace,NaN,C01339
4,Ord-1004,01/06/26,mid-west,C265,03,154.39$,SUP02,Jan 08 2026,usd,web,WINTER5,cust-1259

**2) Load the shipments_raw dataset and inspect the first few rows**

In [4]:
df_shipments = pd.read_excel("supplychain_raw.xlsx", sheet_name="shipments_raw")

displaying head to inspect

In [5]:
df_shipments.head()

,shipment_id_raw,order_id_raw,ship_dt_raw,carrier_raw,whse_raw,qty_shipped_raw,ship_cost_raw,delivery_status_raw,tracking_raw
0,s9001,ORD1000,Jan 22 2026,fx,LAX-1,01,NaN,InTransit,NaN
1,S-9002,ORD1002,2026.01.18,DHL,CHI1,1,NaN,deliv,NaN
2,s9003,ORD1003,2026/01/04,NaN,NJ1,one,009.60,deliv,TRKPKYKSTNECW
3,S-9004,ord-1004,2026.01.13,DHL,NaN,4,10.32$,NaN,TRKV3NRO003MM
4,s9005,ord-1005,01/11/26,usps,LAX1,3 pcs,$17.53,Delayed,NaN

**3) Load the product_master_raw dataset and inspect the first few rows**

In [6]:
df_product = pd.read_excel("supplychain_raw.xlsx", sheet_name="product_master_raw")

Displaying head to inspect

In [7]:
df_product.head()

,sku_raw,category_raw,brand_raw,uom_raw,std_cost_raw,list_price_raw,supplier_raw,discontinued_raw
0,F214,Grocery,UrbanLeaf,EA,"151,90","102,34",SUP-002,N
1,A859,Sports,BrightWare,each,151.223,$200.34,SUP07,N
2,C350,Beauty,UrbanLeaf,PCS,85.43$,"41,73",SUP02,N
3,b242,Sports,BrightWare,PCS,USD 76,USD 61,SUP04,N
4,sku-f204,Sports,ZenithCo,each,"50,67",181.95$,sup-07,N

installing ydata profiling to generate a ProfileReport

In [8]:
pip install ydata_profiling

Collecting ydata_profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata_profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata_profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata_profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (4.67.1)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata_profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (4.4.4)
Collecting imagehash==4.3.2 (from ydata_profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (1.9.5)
Collecting dacite<2,>=1.9 (from ydata_profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata_profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata_profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata_profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata_profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (25.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (3.3.1)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata_profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata_profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata_profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata_profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata_profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata_profiling) (2026.1.4)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata_profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (25.4.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata_profiling)
  Downloading puremagic-1.30-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata_profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 8.2 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 25.7 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 68.3 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 55.2 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 10.9 MB/s eta 0:00:00
Downloading puremagic-1.30-py3-none-any.whl (43 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.3/43.3 kB 4.4 MB/s eta 0:00:00
Installing collected packages: puremagic, minify-html, filetype, multimethod, dacite, imagehash, visions, phik, ydata_profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-1.30 visions-0.8.1 ydata_profiling-4.18.1

importing ProfileReport

In [9]:
from ydata_profiling import ProfileReport

In [10]:
ProfileReport(df_shipments).to_file("shipments_report.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/9 [00:00<?, ?it/s]
 11%|█         | 1/9 [00:00<00:00,  9.44it/s]
 33%|███▎      | 3/9 [00:00<00:00, 14.99it/s]
100%|██████████| 9/9 [00:00<00:00, 20.06it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

**4) Summarize the orders_raw DataFrame**
> Null count

> Null Percentage

> Data Types

> Unique Values

In [11]:
null_counts = df_shipments.isnull().sum()
null_pct = (null_counts / len(df_shipments)) * 100
data_types = df_shipments.dtypes
unique_counts = df_shipments.nunique()
null_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique count": unique_counts})
null_summary

                     null   null_pct Data Types  Unique count
shipment_id_raw         0   0.000000     object          8737
order_id_raw            0   0.000000     object          8128
ship_dt_raw            93   1.064439     object           176
carrier_raw          1074  12.292549     object             7
whse_raw             1094  12.521460     object             7
qty_shipped_raw        87   0.995765     object            17
ship_cost_raw        2265  25.924230     object          1785
delivery_status_raw  1222  13.986494     object             6
tracking_raw         2258  25.844111     object          6479

In [12]:
null_counts = df_orders.isnull().sum()
null_pct = null_counts / len(df_orders) * 100
data_types = df_orders.dtypes
unique_counts = df_orders.nunique()
null_count_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique count": unique_counts})
null_count_summary

                     null  null_pct Data Types  Unique count
order_id_raw            0    0.0000     object          8000
order_dt_raw            0    0.0000     object           160
cust_region_raw         0    0.0000     object             9
sku_raw                 0    0.0000     object          1217
qty_raw                86    1.0750     object            22
unit_price_raw         42    0.5250     object          6458
supplier_raw           77    0.9625     object            40
promise_ship_dt_raw   159    1.9875     object           192
currency_raw         1627   20.3375     object             4
order_channel_raw    1134   14.1750     object             6
promo_code_raw       5975   74.6875     object             4
customer_id_raw       411    5.1375     object          3039

**5) Summarize the shipments_raw DataFrame to review its columns, data types, and overall completeness.**

In [13]:
null_counts = df_shipments.isnull().sum()
null_pct = null_counts / len(df_shipments) * 100
data_types = df_shipments.dtypes
unique_counts = df_shipments.nunique()
null_ship_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique Count": unique_counts})
null_ship_summary

                     null   null_pct Data Types  Unique Count
shipment_id_raw         0   0.000000     object          8737
order_id_raw            0   0.000000     object          8128
ship_dt_raw            93   1.064439     object           176
carrier_raw          1074  12.292549     object             7
whse_raw             1094  12.521460     object             7
qty_shipped_raw        87   0.995765     object            17
ship_cost_raw        2265  25.924230     object          1785
delivery_status_raw  1222  13.986494     object             6
tracking_raw         2258  25.844111     object          6479

**6) Summarize the product_master_raw DataFrame to see all product fields and their data types, checking for completeness**

In [14]:
null_counts = df_product.isnull().sum()
null_pct = null_counts / len(df_product) * 100
data_types = df_product.dtypes
unique_counts = df_product.nunique()
null_ship_summary = pd.DataFrame({'null': null_counts, 'null_pct': null_pct, 'Data Types': data_types, "Unique Count": unique_counts})
null_ship_summary

                  null  null_pct Data Types  Unique Count
sku_raw              0       0.0     object           248
category_raw         0       0.0     object             6
brand_raw            0       0.0     object             6
uom_raw              0       0.0     object             5
std_cost_raw         0       0.0     object           243
list_price_raw       1       0.4     object           245
supplier_raw         1       0.4     object            40
discontinued_raw     4       1.6     object             4

**7. Computing basic statistics for numeric columns on orders_raw for quantity and price**

In [15]:
orders_stats = df_orders[['qty_raw','unit_price_raw']]
orders_stats

     qty_raw unit_price_raw
0      1 pcs        $155.94
1         01          93,99
2          4        139.35$
3      1 pcs         243,48
4         03        154.39$
...      ...            ...
7995   5 pcs        167.46$
7996   1 pcs        $227.80
7997      03         $81.18
7998      01        USD 123
7999      10         76.72$

[8000 rows x 2 columns]

# ERROR RE-*RUNNING* THE CELL??

In [16]:
orders_stats['unit_price_raw'] = (
    orders_stats['unit_price_raw']
    .str.replace('$', '')
    .str.replace(',', '')
    .str.replace('USD', '')
    .astype(float)

)

/tmp/ipython-input-132898487.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_stats['unit_price_raw'] = (

In [17]:
orders_stats.describe()

       unit_price_raw
count     7958.000000
mean      2759.379046
std       6167.931616
min          8.000000
25%         86.709000
50%        165.385000
75%        244.380000
max      25946.000000

In [18]:
df_orders['qty_raw'].describe()

count     7914
unique      22
top          2
freq       888
Name: qty_raw, dtype: object

In [19]:
df_orders['unit_price_raw'].describe()

count        7958
unique       6458
top       USD 152
freq           15
Name: unit_price_raw, dtype: object

**8) Statistical summaries for numerical feilds in products_master_raw over numerical columns**

In [20]:
products_stats = df_product[['std_cost_raw', 'list_price_raw']]
products_stats

    std_cost_raw list_price_raw
0         151,90         102,34
1        151.223        $200.34
2         85.43$          41,73
3         USD 76         USD 61
4          50,67        181.95$
..           ...            ...
245        62,89        229.295
246      USD 148         USD 13
247       USD 22         175,87
248      $152.67         77.851
249       24.693        231.48$

[250 rows x 2 columns]

In [21]:
products_stats['std_cost_raw'] = (
    products_stats['std_cost_raw']
    .str.replace('$', '')
    .str.replace(',', '.')
    .str.replace('USD', '')
    .astype(float)
)

/tmp/ipython-input-1072866758.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_stats['std_cost_raw'] = (

In [22]:
products_stats['list_price_raw'] = (
    products_stats['list_price_raw']
    .str.replace('$', '')
    .str.replace(',', '.')
    .str.replace('USD', '')
    .astype(float)
)

/tmp/ipython-input-2552790043.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products_stats['list_price_raw'] = (

In [23]:
products_stats.describe()

       std_cost_raw  list_price_raw
count    250.000000      249.000000
mean      87.198204      123.878486
std       50.411199       70.652268
min        4.590000        6.130000
25%       42.857500       61.000000
50%       84.895000      125.000000
75%      134.315000      181.410000
max      179.950000      249.234000

9) Identify which columns in orders_raw have missing values and how many, to assess data completeness for order records.

> focusing on critical ones like order_id, customer_id, product_id

In [24]:
orders_missing = df_orders[['order_id_raw', 'customer_id_raw', 'order_id_raw']]
orders_missing

     order_id_raw customer_id_raw order_id_raw
0        ORD-1000          C00583     ORD-1000
1        Ord-1001          C00029     Ord-1001
2        ORD1002           C00288     ORD1002
3        ORD1003           C01339     ORD1003
4        Ord-1004       cust-1259     Ord-1004
...           ...             ...          ...
7995     ORD8995           C00685     ORD8995
7996     Ord-8996          C00381     Ord-8996
7997     ORD-8997          C00486     ORD-8997
7998       o-8998          C01697       o-8998
7999     Ord-8999       cust-1734     Ord-8999

[8000 rows x 3 columns]

In [25]:
nulls_in_orders = orders_missing.isnull().sum()
nulls_pct = nulls_in_orders / len(orders_missing) * 100
df_missing = pd.DataFrame({'null': nulls_in_orders, 'null_pct': nulls_pct})
df_missing

                 null  null_pct
order_id_raw        0    0.0000
customer_id_raw   411    5.1375
order_id_raw        0    0.0000

In [26]:
orders_missing[orders_missing['customer_id_raw'].isna()]

     order_id_raw customer_id_raw order_id_raw
13       ORD-1013             NaN     ORD-1013
23       ORD-1023             NaN     ORD-1023
98         o-1098             NaN       o-1098
101      ORD-1101             NaN     ORD-1101
108        o-1108             NaN       o-1108
...           ...             ...          ...
7929     ORD 8929             NaN     ORD 8929
7931     ORD8931              NaN     ORD8931
7933       o-8933             NaN       o-8933
7950       o-8950             NaN       o-8950
7958     ord-8958             NaN     ord-8958

[411 rows x 3 columns]

**10) Identify missing values in shipments_raw and count them to determine if any shipping information is incomplete.**

> shipments_raw (e.g., shipment_date, carrier, other relevant fields)

In [27]:
missing_shipment_details = df_shipments[['ship_dt_raw', 'carrier_raw']]
missing_shipment_details

      ship_dt_raw carrier_raw
0     Jan 22 2026          fx
1      2026.01.18        DHL
2      2026/01/04         NaN
3      2026.01.13        DHL
4        01/11/26        usps
...           ...         ...
8732   24-01-2026        UP S
8733     20260110          fx
8734  Jan 15 2026         UPS
8735  Jan 03 2026          fx
8736    19-Jan-26         NaN

[8737 rows x 2 columns]

In [28]:
missing_shipment_details['ship_dt_raw'] = (
    missing_shipment_details['ship_dt_raw']
    .str.replace('/', '-')
    .str.replace('Jan', '02')
    .str.replace(' ', '-')
    .str.replace(',', '-')
    .str.replace('.', '-')
)

/tmp/ipython-input-628152831.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['ship_dt_raw'] = (

In [29]:
missing_shipment_details['ship_dt_raw']

0       02-22-2026
1       2026-01-18
2       2026-01-04
3       2026-01-13
4         01-11-26
           ...
8732    24-01-2026
8733      20260110
8734    02-15-2026
8735    02-03-2026
8736      19-02-26
Name: ship_dt_raw, Length: 8737, dtype: object

In [30]:
missing_shipment_details['ship_dt_raw'] = pd.to_datetime(missing_shipment_details['ship_dt_raw'], format= "mixed")

/tmp/ipython-input-4002348276.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['ship_dt_raw'] = pd.to_datetime(missing_shipment_details['ship_dt_raw'], format= "mixed")

In [31]:
missing_shipment_details['ship_dt_raw'].isna()

0       False
1       False
2       False
3       False
4       False
        ...
8732    False
8733    False
8734    False
8735    False
8736    False
Name: ship_dt_raw, Length: 8737, dtype: bool

> Identified the missing [ship_dt_raw] dates rows

In [32]:
missing_shipment_details[missing_shipment_details['ship_dt_raw'].isna()]

     ship_dt_raw carrier_raw
194          NaT        USPS
200          NaT         NaN
211          NaT        DHL
283          NaT        UP S
318          NaT         UPS
...          ...         ...
8112         NaT        usps
8322         NaT        usps
8353         NaT        DHL
8606         NaT        usps
8651         NaT         NaN

[93 rows x 2 columns]

In [33]:
missing_shipment_details['carrier_raw'] = missing_shipment_details['carrier_raw'].fillna('Unknown')

/tmp/ipython-input-771470343.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['carrier_raw'] = missing_shipment_details['carrier_raw'].fillna('Unknown')

In [34]:
missing_shipment_details['carrier_raw'] = (
    missing_shipment_details['carrier_raw']
    .str.replace(' ', '')
    .str.replace('fx', 'FEDEX')
    .str.replace('usps', 'USPS')
    .str.replace('ups', 'UPS')
    .str.replace('fedex', 'FEDEX')
    .astype(str)
)

/tmp/ipython-input-3435429000.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  missing_shipment_details['carrier_raw'] = (

In [35]:
missing_shipment_details['carrier_raw']

0         FEDEX
1           DHL
2       Unknown
3           DHL
4          USPS
         ...
8732        UPS
8733      FEDEX
8734        UPS
8735      FEDEX
8736    Unknown
Name: carrier_raw, Length: 8737, dtype: object

> Identified nulls and handled nulls with replacing as unknown carrier

In [36]:
missing_shipment_details['carrier_raw'].isna().sum()

np.int64(0)

**11) Identify missing values in product_master_raw (for instance, missing product prices or categories) and quantify them to ensure product data completeness.**

> product_master_raw (e.g., price, category, name)

In [53]:
missing_product_details = df_product[['category_raw', 'brand_raw', 'std_cost_raw']].head()
missing_product_details

  category_raw   brand_raw std_cost_raw
0      Grocery   UrbanLeaf       151,90
1       Sports  BrightWare      151.223
2       Beauty   UrbanLeaf       85.43$
3       Sports  BrightWare       USD 76
4       Sports    ZenithCo        50,67

In [62]:
df_product[['category_raw', 'brand_raw', 'std_cost_raw']].duplicated().sum()

np.int64(0)

**12) Check for any duplicate records in orders_raw by looking for repeated order IDs, ensuring each order is uniquely recorded.**
 > Datasets & Columns: orders_raw (order_id)

In [63]:
df_orders['order_id_raw'].duplicated().sum()

np.int64(0)

**13) Check for duplicate entries in shipments_raw (e.g., by a shipment identifier or combination of order_id and other fields) to ensure each shipment is recorded only once.**
 > Datasets & Columns: shipments_raw (shipment_id or composite key like order_id + shipment_date)

In [64]:
df_shipments['shipment_id_raw'].duplicated().sum()

np.int64(0)

**14) Confirm that product_master_raw contains unique products by verifying no duplicate product_id values exist.**
> Datasets & Columns: product_master_raw (product_id)

In [68]:
clean_sku = df_product['sku_raw']

In [70]:
clean_sku = clean_sku.str.replace('SKU-', '')

In [78]:
clean_sku = clean_sku.str.replace('sku-', '')

In [91]:
clean_sku.nunique() == len(clean_sku)

False

In [92]:
clean_sku.duplicated().sum()

np.int64(2)

In [93]:
clean_sku.isna().sum()

np.int64(0)

In [96]:
df_product[clean_sku.duplicated()]

,sku_raw,category_raw,brand_raw,uom_raw,std_cost_raw,list_price_raw,supplier_raw,discontinued_raw
119,SKU-B652,Grocery,UrbanLeaf,each,39.638,$208.40,SUP09,N
178,b294,Apparel,BlueRock,each,"11,22",$167.93,SUP-08,N

15) Verify that all product IDs in orders_raw correspond to an existing product in product_master_raw, ensuring referential integrity between orders and products.

>  Datasets & Columns: orders_raw (product_id), product_master_raw (product_id)

In [97]:
df_orders['sku_raw'].isin(clean_sku).value_counts()

sku_raw
False    6277
True     1723
Name: count, dtype: int64

In [107]:
clean_sku_orders = df_orders['sku_raw']

In [108]:
clean_sku_orders

0        SKU-A499
1            a354
2           D674
3            E846
4            C265
          ...
7995        A878
7996     sku-e559
7997     sku-a924
7998         c691
7999         A683
Name: sku_raw, Length: 8000, dtype: object

In [112]:
clean_sku_orders = clean_sku_orders.str.replace('SKU-', '')

In [113]:
clean_sku_orders = clean_sku_orders.str.replace('sku-', '')

In [118]:
df_orders['sku_raw'] = clean_sku_orders

In [126]:
df_orders['sku_raw'].isin(df_product['sku_raw']).value_counts()

sku_raw
False    6394
True     1606
Name: count, dtype: int64

16) Verify that every order_id in shipments_raw exists in orders_raw, confirming that all recorded shipments relate to actual orders.
 > Datasets & Columns: shipments_raw (order_id), orders_raw (order_id)

In [127]:
def clean_order_id(col):
    col = col.str.replace('ORD-', '')
    col = col.str.replace('Ord-', '')
    col = col.str.replace('ord-', '')
    col = col.str.replace('o-', '')
    col = col.str.replace('O-', '')
    col = col.str.replace(' ', '')
    col = col.str.replace('ord', '')
    col = col.str.replace('ORD', '')
    return col

In [128]:
cleann = clean_order_id(df_shipments['order_id_raw'])

In [129]:
clean_order_id(df_orders['order_id_raw'])

0       1000
1       1001
2       1002
3       1003
4       1004
        ...
7995    8995
7996    8996
7997    8997
7998    8998
7999    8999
Name: order_id_raw, Length: 8000, dtype: object

In [130]:
clean_order_id(df_shipments['order_id_raw'])

0         1000
1         1002
2         1003
3         1004
4         1005
         ...
8732    991439
8733    995706
8734    991419
8735    997677
8736    992394
Name: order_id_raw, Length: 8737, dtype: object

In [133]:
df_shipments['order_id_raw'].isin(df_orders['order_id_raw']).value_counts()

order_id_raw
True     4934
False    3803
Name: count, dtype: int64

**17) Ensure numeric values in orders_raw are valid (for example, quantities and prices should be positive and within reasonable ranges) to catch any data entry errors.**
 > Datasets & Columns: orders_raw (quantity, price)

In [139]:
df_orders[['qty_raw', 'unit_price_raw']]

     qty_raw unit_price_raw
0      1 pcs        $155.94
1         01          93,99
2          4        139.35$
3      1 pcs         243,48
4         03        154.39$
...      ...            ...
7995   5 pcs        167.46$
7996   1 pcs        $227.80
7997      03         $81.18
7998      01        USD 123
7999      10         76.72$

[8000 rows x 2 columns]

In [171]:
df_orders['qty_raw'] = (
    df_orders['qty_raw']
    .str.replace('pcs', '')
    .str.replace(' ', '')
    .str.replace('one', '1')
)

In [193]:
df_orders['unit_price_raw'] = (
     df_orders['unit_price_raw']
    .str.replace(' ', '')
    .str.replace('$', '')
    .str.replace('USD', '')
    .str.replace('usd', '')
    .str.replace(',', '.')
)

In [194]:
df_orders[['qty_raw', 'unit_price_raw']]

      qty_raw unit_price_raw
0         1.0         155.94
1         1.0           9399
2         4.0         139.35
3         1.0          24348
4         3.0         154.39
...       ...            ...
7995      5.0         167.46
7996      1.0         227.80
7997      3.0          81.18
7998      1.0            123
7999     10.0          76.72

[8000 rows x 2 columns]

In [195]:
df_orders['qty_raw'].astype(float).describe()

count    7914.000000
mean        3.171721
std         2.533377
min        -1.000000
25%         1.000000
50%         2.000000
75%         4.000000
max        10.000000
Name: qty_raw, dtype: float64

In [196]:
df_orders['unit_price_raw'].astype(float).describe()

count     7958.000000
mean      2759.379046
std       6167.931616
min          8.000000
25%         86.709000
50%        165.385000
75%        244.380000
max      25946.000000
Name: unit_price_raw, dtype: float64

**19) Confirm that all products have essential details in product_master_raw (for instance, each product has a non-missing price and a category assigned).**
> Datasets & Columns: product_master_raw (price, category)

In [192]:
df_product[['std_cost_raw', 'category_raw']]

    std_cost_raw category_raw
0         151,90      Grocery
1        151.223       Sports
2         85.43$       Beauty
3         USD 76       Sports
4          50,67       Sports
..           ...          ...
245        62,89       Beauty
246      USD 148      Apparel
247       USD 22       Sports
248      $152.67       Beauty
249       24.693      Grocery

[250 rows x 2 columns]

In [198]:
df_product['std_cost_raw'] = (
     df_product['std_cost_raw']
    .str.replace(' ', '')
    .str.replace('$', '')
    .str.replace('USD', '')
    .str.replace('usd', '')
    .str.replace(',', '.')
)

In [207]:
df_product['std_cost_raw'].isna().sum()

np.int64(0)

In [206]:
df_product['category_raw'].isna().sum()

np.int64(0)

**20) Count the number of distinct products that appear in orders_raw to see how many different items have been sold.**
 > Datasets & Columns: orders_raw (product_id)

In [218]:
df_orders['sku_raw'] = clean_sku_orders

In [219]:
df_orders['sku_raw'].isna().sum()

np.int64(0)

In [220]:
df_orders['sku_raw'].nunique()

974

**21)Determine the total number of products listed in product_master_raw to understand the size of the product catalog.**
> Datasets & Columns: product_master_raw (product_id)

In [221]:
df_product['sku_raw'] = clean_sku_orders

In [222]:
df_product['sku_raw'].nunique()

221

**22) Count the number of unique customers in orders_raw to measure the customer base captured in the dataset.**
> Datasets & Columns: orders_raw (customer_id)

In [223]:
df_orders['customer_id_raw']

0          C00583
1          C00029
2          C00288
3          C01339
4       cust-1259
          ...
7995       C00685
7996       C00381
7997       C00486
7998       C01697
7999    cust-1734
Name: customer_id_raw, Length: 8000, dtype: object

In [224]:
df_orders['customer_id_raw'] = (
    df_orders['customer_id_raw']
    .str.replace('CUST-', 'C00')
    .str.replace('cust-', 'C00')
    .str.replace('Cust-', 'C00')
)

In [233]:
df_orders[df_orders['customer_id_raw'].isna()] #Null values can be handled according to business rules

,order_id_raw,order_dt_raw,cust_region_raw,sku_raw,qty_raw,unit_price_raw,supplier_raw,promise_ship_dt_raw,currency_raw,order_channel_raw,promo_code_raw,customer_id_raw
13,ORD-1013,12-Jan-26,US-West,C266,2.0,91.916,SUP02,2026-01-16,US$,WEB,NaN,NaN
23,ORD-1023,2026-01-01,MIDWEST,F155,1.0,23,NaN,20260105,usd,web,NaN,NaN
98,o-1098,01/10/26,west,b830,1.0,24889,SUP-03,11-01-2026,US$,WEB,NEW10,NaN
101,ORD-1101,2026-01-20,MIDWEST,A214,1.0,154.91,SUP02,23-Jan-26,$,app,NaN,NaN
108,o-1108,2026.01.03,MIDWEST,A109,5.0,92.02,SUP08,20260105,USD,Marketplace,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
7929,ORD 8929,10-Jan-26,us east,b786,5.0,225.97,SUP-08,Jan 13 2026,USD,mobile,NaN,NaN
7931,ORD8931,09-01-2026,west,b267,-1.0,106.76,SUP-004,2026/01/10,NaN,WEB,NaN,NaN
7933,o-8933,01/12/26,us east,f533,3.0,25712,SUP07,20260117,NaN,web,NaN,NaN
7950,o-8950,2026-01-11,SOUTH,D318,1.0,23.183,SUP02,2026/01/12,US$,NaN,FREESHIP,NaN
7958,ord-8958,2026-01-19,MW,D649,1.0,122.09,SUP03,20260124,$,app,NaN,NaN

In [229]:
df_orders['customer_id_raw'].nunique()

2561

**23)List all distinct shipping methods or carriers used in shipments_raw to see the variety of delivery options utilized.**
>  Datasets & Columns: shipments_raw (shipping_method or carrier)

In [236]:
df_shipments['carrier_raw'] = missing_shipment_details['carrier_raw']

In [240]:
df_shipments['carrier_raw'].unique()

array(['FEDEX', 'DHL', 'Unknown', 'USPS', 'UPS'], dtype=object)

**24)List the distinct product categories present in product_master_raw to understand the range of product types offered.**
> Datasets & Columns: product_master_raw (category)

In [241]:
df_product['category_raw']

0      Grocery
1       Sports
2       Beauty
3       Sports
4       Sports
        ...
245     Beauty
246    Apparel
247     Sports
248     Beauty
249    Grocery
Name: category_raw, Length: 250, dtype: object

In [244]:
df_product['category_raw'].isnull().sum()

np.int64(0)

In [243]:
df_product['category_raw'].unique()

array(['Grocery', 'Sports', 'Beauty', 'Home', 'Apparel', 'Electronics'],
      dtype=object)

**25) Identify the earliest and latest order dates in orders_raw to establish the time span of the sales data.**

> Datasets & Columns: orders_raw (order_date)

In [247]:
df_orders['order_dt_raw'] = missing_shipment_details['ship_dt_raw']

In [252]:
missing_shipment_details[missing_shipment_details['ship_dt_raw'].isnull()]

     ship_dt_raw carrier_raw
194          NaT        USPS
200          NaT     Unknown
211          NaT         DHL
283          NaT         UPS
318          NaT         UPS
...          ...         ...
8112         NaT        USPS
8322         NaT        USPS
8353         NaT         DHL
8606         NaT        USPS
8651         NaT     Unknown

[93 rows x 2 columns]

In [256]:
missing_date_rows_Flag = missing_shipment_details[missing_shipment_details['ship_dt_raw'].isnull()]

In [257]:
missing_date_rows_Flag #can be handled according to business rules

     ship_dt_raw carrier_raw
194          NaT        USPS
200          NaT     Unknown
211          NaT         DHL
283          NaT         UPS
318          NaT         UPS
...          ...         ...
8112         NaT        USPS
8322         NaT        USPS
8353         NaT         DHL
8606         NaT        USPS
8651         NaT     Unknown

[93 rows x 2 columns]

In [258]:
Valid_date_rows = missing_shipment_details[missing_shipment_details['ship_dt_raw'].notnull()]

In [260]:
Valid_date_rows # valid dated rows for analysis

     ship_dt_raw carrier_raw
0     2026-02-22       FEDEX
1     2026-01-18         DHL
2     2026-01-04     Unknown
3     2026-01-13         DHL
4     2026-01-11        USPS
...          ...         ...
8732  2026-01-24         UPS
8733  2026-01-10       FEDEX
8734  2026-02-15         UPS
8735  2026-02-03       FEDEX
8736  2026-02-19     Unknown

[8644 rows x 2 columns]

In [261]:
Valid_date_rows['ship_dt_raw'].sort_values()

5748   2026-01-03
4745   2026-01-03
3767   2026-01-03
1604   2026-01-03
7655   2026-01-03
          ...
3000   2026-12-02
6947   2026-12-02
7270   2026-12-02
3270   2026-12-02
6156   2026-12-02
Name: ship_dt_raw, Length: 8644, dtype: datetime64[ns]

In [278]:
minimum_date_orders = Valid_date_rows['ship_dt_raw'].min()

In [279]:
maximum_date_orders = Valid_date_rows['ship_dt_raw'].max()

In [280]:
minimum_date_orders, maximum_date_orders

(Timestamp('2026-01-03 00:00:00'), Timestamp('2026-12-02 00:00:00'))

**26)Identify the earliest and latest shipment dates in shipments_raw to understand the timeframe of shipping activities and align it with the order dates.**
> Datasets & Columns: shipments_raw (shipment_date)

In [283]:
df_shipments['ship_dt_raw']

0       Jan 22 2026
1        2026.01.18
2        2026/01/04
3        2026.01.13
4          01/11/26
           ...
8732     24-01-2026
8733       20260110
8734    Jan 15 2026
8735    Jan 03 2026
8736      19-Jan-26
Name: ship_dt_raw, Length: 8737, dtype: object

In [284]:
df_shipments['ship_dt_raw'] = (
    df_shipments['ship_dt_raw']
    .str.replace('/', '-')
    .str.replace('Jan', '02')
    .str.replace(' ', '-')
    .str.replace(',', '-')
    .str.replace('.', '-')
)

In [287]:
df_shipments['ship_dt_raw'] = pd.to_datetime(df_shipments['ship_dt_raw'], format= "mixed")

In [288]:
df_shipments['ship_dt_raw']

0      2026-02-22
1      2026-01-18
2      2026-01-04
3      2026-01-13
4      2026-01-11
          ...
8732   2026-01-24
8733   2026-01-10
8734   2026-02-15
8735   2026-02-03
8736   2026-02-19
Name: ship_dt_raw, Length: 8737, dtype: datetime64[ns]

In [289]:
min_ship_date = df_shipments['ship_dt_raw'].min()
max_ship_date = df_shipments['ship_dt_raw'].max()

In [290]:
min_ship_date, max_ship_date

(Timestamp('2026-01-03 00:00:00'), Timestamp('2026-12-02 00:00:00'))

In [291]:
minimum_date_orders == min_ship_date

True

In [292]:
maximum_date_orders == max_ship_date

True

**27)Filter the orders_raw dataset to find orders with a quantity above a high threshold (for example, > 10 units) to spot bulk purchase orders.**
> Datasets & Columns: orders_raw (quantity)

In [315]:
df_orders['qty_raw']

0        1.0
1        1.0
2        4.0
3        1.0
4        3.0
        ...
7995     5.0
7996     1.0
7997     3.0
7998     1.0
7999    10.0
Name: qty_raw, Length: 8000, dtype: float64

In [330]:
filtered_qty = df_orders[df_orders['qty_raw'] >= 10.0]

In [331]:
filtered_qty

,order_id_raw,order_dt_raw,cust_region_raw,sku_raw,qty_raw,unit_price_raw,supplier_raw,promise_ship_dt_raw,currency_raw,order_channel_raw,promo_code_raw,customer_id_raw
20,ORD1020,2026-01-04,MW,E202,10.0,15241,SUP02,2026-01-08,USD,store,FREESHIP,C001770
25,Ord-1025,2026-01-06,south,b242,10.0,213.12,SUP04,2026.01.18,NaN,app,NaN,C00765
28,ORD-1028,2026-02-24,MIDWEST,b834,10.0,130.94,SUP01,2026-01-14,US$,mobile,NaN,C001903
30,o-1030,2026-01-18,MW,A878,10.0,20630,SUP-009,2026/01/13,USD,WEB,NaN,C00698
33,ORD1033,2026-02-15,mid-west,D703,10.0,193.852,SUP04,2026-01-18,$,NaN,NEW10,C00184
...,...,...,...,...,...,...,...,...,...,...,...,...
7953,ord-8953,2026-02-19,SOUTH,F765,10.0,57.022,SUP02,21-Jan-26,$,Marketplace,FREESHIP,C01875
7959,Ord-8959,2026-02-08,mid-west,b532,10.0,11.65,sup-01,06-01-2026,$,store,NaN,C00766
7983,ord-8983,2026-02-08,US-East,f206,10.0,203.415,SUP-007,Jan 19 2026,US$,mobile,NaN,C00983
7988,Ord-8988,2026-02-19,us east,A924,10.0,141,SUP-006,01/22/26,$,NaN,NaN,C00266
7999,Ord-8999,2026-01-14,MIDWEST,A683,10.0,76.72,SUP-004,2026/01/23,usd,Marketplace,NaN,C001734

**28)Filter the shipments_raw data for shipments handled by a specific carrier (e.g., only those shipped via "ExpressShip") to isolate that carrier’s shipments.**
> Datasets & Columns: shipments_raw (carrier or shipping_method)

In [335]:
df_shipments['carrier_raw']

0         FEDEX
1           DHL
2       Unknown
3           DHL
4          USPS
         ...
8732        UPS
8733      FEDEX
8734        UPS
8735      FEDEX
8736    Unknown
Name: carrier_raw, Length: 8737, dtype: object

In [336]:
df_shipments[df_shipments['carrier_raw'] == 'FEDEX']

,shipment_id_raw,order_id_raw,ship_dt_raw,carrier_raw,whse_raw,qty_shipped_raw,ship_cost_raw,delivery_status_raw,tracking_raw
0,s9001,ORD1000,2026-02-22,FEDEX,LAX-1,01,NaN,InTransit,NaN
5,S-9006,Ord-1006,2026-01-18,FEDEX,DAL-1,4 pcs,NaN,DELIVERED,TRK2YPH3VCW0I
9,S-9010,ord-1010,2026-01-23,FEDEX,chi-1,2,USD 13,DLVD,NaN
11,S9012,ord-1012,2026-01-09,FEDEX,nj-1,one,NaN,Delayed,NaN
12,S9013,ORD1013,2026-01-10,FEDEX,NaN,4,009.60,deliv,TRKLXW7JW0PEO
...,...,...,...,...,...,...,...,...,...
8728,S17729,ORD-998356,2026-01-22,FEDEX,LAX-1,1 pcs,20.209,NaN,NaN
8730,S17731,ORD-999531,2026-02-23,FEDEX,LAX-1,01,USD 29,NaN,NaN
8731,S17732,ORD-999255,2026-01-04,FEDEX,chi-1,1 pcs,18.492,InTransit,NaN
8733,S17734,ORD-995706,2026-01-10,FEDEX,NaN,one,"18,41",deliv,NaN
8735,S17736,ORD-997677,2026-02-03,FEDEX,DAL-1,one,9.36$,Delayed,NaN